# Generated by Django 4.1.4 on 2023-01-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0, max_length=20, verbose_name='Рейтинг'),
        ),
    ]
